/*
  Visualizing the Panasonic Grid-EYE Sensor Data using Processing
 Synerflight Forked version of  Nick Poole Grideye
  SparkFun Electronics
  Date: January 12th, 2018
  
  MIT License: Permission is hereby granted, free of charge, to any person obtaining a copy of this 
  software and associated documentation files (the "Software"), to deal in the Software without 
  restriction, including without limitation the rights to use, copy, modify, merge, publish, 
  distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the 
  Software is furnished to do so, subject to the following conditions:

  The above copyright notice and this permission notice shall be included in all copies or 
  substantial portions of the Software.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING 
  BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND 
  NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, 
  DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, 
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
  
  Feel like supporting our work? Buy a board from SparkFun!
  https://www.sparkfun.com/products/14568
  
  This example is intended as a companion sketch to the Processing sketch found in the same folder.
  Once this code is running on your hardware, open the accompanying Processing sketch and run it 
  as well. The Processing sketch will receive the comma separated values generated by this code and
  use them to generate a thermal image. If you don't have Processing, you can download it here:
  https://processing.org/
  
  Hardware Connections:
  Attach the Sensor to the Arduino accordingly

 SDA - A4
 SCL - A5
 D9 - PWM out to Flight controler
 Serial0 - to Telemetry (bluetooth)
 TX-Rx
 Rx-Tx
 Vcc-Vin
 Gnd-Gnd
 
  Attach the Arduino D9 to Synerduino shield A15
  D9 - A15
  Vcc - (+)
  Gnd - (-)
  
*/
#include <Servo.h>
Servo servo_pin_9;
#include <Wire.h>
#include <SparkFun_GridEYE_Arduino_Library.h>

GridEYE grideye;

void setup() {

  // Start your preferred I2C object 
  Wire.begin();
  // Library assumes "Wire" for I2C but you can pass something else with begin() if you like
  grideye.begin();
  // Pour a bowl of serial // baud rate must be similar on Arduino, Telemetry ,Processing software
 Serial.begin(115200); 
 //Serial.begin(57600);
 //Serial.begin(38400);

 servo_pin_9.attach(9);
}

void loop() {
//--Hotpix--
  float testPixelValue = 0;
  float hotPixelValue = 0;
  int hotPixelIndex = 0;
  
//--thermal--
  // Print the temperature value of each pixel in floating point degrees Celsius
  // separated by commas 
  for(unsigned char i = 0; i < 64; i++){
    Serial.print(grideye.getPixelTemperature(i));
    Serial.print(",");

    testPixelValue = grideye.getPixelTemperature(i);
      if(testPixelValue > hotPixelValue){
        hotPixelValue = testPixelValue;
        hotPixelIndex = i;
      }
   servo_pin_9.write( ( hotPixelValue + 43 ) );// change tuning (hotPixelValue + "VALUE#") this to adjust the pwm out put to the Aux //Ex: 20c Degrees = 1200ms PWM  
  } 

  // End each frame with a linefeed
  Serial.println();

  // Give Processing time to chew
  delay(80);


  

}
